-- Captured from the schema Hibernate's ddl-auto=update had created, so this
-- reproduces the existing database exactly. Improvements go in later migrations.
CREATE TABLE player_data (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age              integer,
    expected_assists double precision,
    assists          integer,
    red_cards        integer,
    yellow_cards     integer,
    goals            integer,
    expected_goals   double precision,
    minutes_played   integer,
    matches_played   integer,
    player_name      varchar(255),
    nation           varchar(255),
    penalties_scored integer,
    "position"       varchar(255),
    starts           integer,
    team_name        varchar(255)
);