-- Gives the schema a time dimension.
--
-- player_data stores conclusions ("Pavlidis has 17 goals") and is overwritten on every
-- load, which is why no season history exists. These tables store events instead ("in
-- match X, Pavlidis played 90 minutes and scored 1"), so totals become a query and the
-- evolution of a player across a season becomes answerable.
--
-- This migration only ADDS. player_data is left untouched and the API keeps reading from
-- it, so the live site cannot go dark while the new tables are still empty. Moving the
-- reads across, and eventually dropping player_data, are separate later migrations.

-- Every table fed from outside carries the identifier its source gave it, so ingestion
-- can ask "have I seen this before?" without matching on names — which is fragile for
-- players (accents, abbreviations, namesakes) and worse for matches. The pair names *a*
-- source rather than naming SofaScore, so a second source can coexist and replacing the
-- source does not change the schema.

CREATE TABLE season (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(20)  NOT NULL,
    source     varchar(20)  NOT NULL,
    source_ref varchar(50)  NOT NULL,
    CONSTRAINT season_name_unique   UNIQUE (name),
    CONSTRAINT season_source_unique UNIQUE (source, source_ref)
);

CREATE TABLE team (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(80)  NOT NULL,
    source     varchar(20)  NOT NULL,
    source_ref varchar(50)  NOT NULL,
    CONSTRAINT team_source_unique UNIQUE (source, source_ref)
);

CREATE TABLE player (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(120) NOT NULL,
    -- ISO 3166-1 alpha-3, which is what the source returns. Replaces the "uy URU" string
    -- the old table stored and filtered with endsWith.
    country_code char(3),
    -- The birth date, not the age: an age is right for at most a year and then lies
    -- silently. Age is derived when it is displayed.
    born         date,
    "position"   varchar(10),
    source       varchar(20)  NOT NULL,
    source_ref   varchar(50)  NOT NULL,
    CONSTRAINT player_source_unique UNIQUE (source, source_ref)
);

CREATE TABLE match (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id    integer      NOT NULL REFERENCES season (id),
    matchday     smallint     NOT NULL,
    -- timestamptz, not timestamp: the source gives a unix instant, and kick-off times
    -- cross a daylight-saving boundary twice a season.
    kickoff_at   timestamptz  NOT NULL,
    home_team_id integer      NOT NULL REFERENCES team (id),
    away_team_id integer      NOT NULL REFERENCES team (id),
    -- Null until the match has been played, so fixtures can be stored before results.
    home_score   smallint,
    away_score   smallint,
    source       varchar(20)  NOT NULL,
    source_ref   varchar(50)  NOT NULL,
    CONSTRAINT match_source_unique UNIQUE (source, source_ref),
    CONSTRAINT match_teams_differ  CHECK (home_team_id <> away_team_id)
);

CREATE TABLE player_match_stat (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id         integer  NOT NULL REFERENCES match (id) ON DELETE CASCADE,
    player_id        integer  NOT NULL REFERENCES player (id),
    -- The team is a property of the performance, not of the person: a January transfer
    -- must not rewrite which shirt he wore in October.
    team_id          integer  NOT NULL REFERENCES team (id),
    is_starter       boolean  NOT NULL,
    minutes_played   smallint NOT NULL,
    -- Deliberately NOT NULL with no DEFAULT. A default of 0 would let ingestion that
    -- dropped a field write a plausible-looking zero, which is precisely how the old
    -- scraper lost the expected-goals columns without anyone noticing. With no default
    -- the insert fails and says which column was never given a value.
    goals            smallint NOT NULL,
    assists          smallint NOT NULL,
    penalties_scored smallint NOT NULL,
    yellow_cards     smallint NOT NULL,
    red_cards        smallint NOT NULL,
    -- Nullable, and decimal: xG is 23.30, not 23. Older seasons genuinely lack it, which
    -- is a different thing from a zero and has to stay distinguishable.
    expected_goals   numeric(5,2),
    expected_assists numeric(5,2),
    -- A third-party composite metric, kept as the source reports it.
    rating           numeric(4,2),
    -- The natural key, and the reason re-running an ingestion is harmless: one row is one
    -- player in one match. Made of columns that come from the data — never of id, which
    -- is generated fresh on every insert and so can never collide.
    CONSTRAINT player_match_stat_unique UNIQUE (match_id, player_id)
);

-- UNIQUE(match_id, player_id) already indexes lookups by match. These cover the other
-- two access paths: one player's season, and ordering a season by matchday.
CREATE INDEX idx_player_match_stat_player ON player_match_stat (player_id);
CREATE INDEX idx_player_match_stat_team   ON player_match_stat (team_id);
CREATE INDEX idx_match_season_matchday    ON match (season_id, matchday);
